{
	"version": 1566285785,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/toolscard-sheet0.png",
		"images/toolscard-sheet1.png",
		"images/mainplace-sheet0.png",
		"images/mainplace-sheet1.png",
		"images/wallwall-sheet0.png",
		"images/mainhanger-sheet0.png",
		"images/mainsum.png",
		"images/toolsscore.png",
		"images/goretry-sheet0.png",
		"images/mainsumback-sheet0.png",
		"images/mainsumback-sheet1.png",
		"images/maincardlight-sheet0.png",
		"images/settingsback-sheet0.png",
		"images/settingssound-sheet0.png",
		"images/settingssound-sheet1.png",
		"images/settingsmusic-sheet0.png",
		"images/settingsmusic-sheet1.png",
		"images/settingsaboutus-sheet0.png",
		"images/toolsicons-sheet0.png",
		"images/toolstextback-sheet0.png",
		"images/maintouchholder-sheet0.png",
		"images/toolstouchholder-sheet0.png",
		"images/toolsbackportrait.png",
		"images/toolsstrip.png",
		"images/loadingmusic-sheet0.png",
		"images/loadingmusic-sheet1.png",
		"images/loadingabout-sheet0.png",
		"images/loadingsound-sheet0.png",
		"images/loadingsound-sheet1.png",
		"images/loadingplay-sheet0.png",
		"images/loadinglogo-sheet0.png",
		"images/loadingprogressback-sheet0.png",
		"images/loadingprogress_.png",
		"images/loadingbestlabel2-sheet0.png",
		"images/loadingbestback-sheet0.png",
		"images/loadingbackground.png",
		"images/loadingbestlabel1-sheet0.png",
		"images/gobackground.png",
		"images/gologo-sheet0.png",
		"images/goscorelabel-sheet0.png",
		"images/goscoreback-sheet0.png",
		"images/goscore.png",
		"media/click.m4a",
		"media/click.ogg",
		"media/pick up cards.m4a",
		"media/pick up cards.ogg",
		"media/place down cards.m4a",
		"media/place down cards.ogg",
		"media/convert cards to ace.m4a",
		"media/convert cards to ace.ogg",
		"media/neon.m4a",
		"media/neon.ogg",
		"media/rotate.m4a",
		"media/rotate.ogg",
		"media/gift.m4a",
		"media/gift.ogg",
		"media/reach.m4a",
		"media/reach.ogg",
		"media/wheel_01.m4a",
		"media/wheel_01.ogg",
		"media/popup21.m4a",
		"media/popup21.ogg",
		"media/music.m4a",
		"media/music.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}